services:

  db1:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: michel
      MARIADB_DATABASE: webserver1db
    networks:
      - webserver1-network

  db2:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: michel
      MARIADB_DATABASE: webserver2db
    networks:
      - webserver2-network

  db3:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: michel
      MARIADB_DATABASE: webserver3db
    networks:
      - webserver3-network

  webserver1: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    environment:
      - DB_HOST=db1
      - DB_NAME=webserver1db
    networks:
      - webserver1-network
      - app-network

  webserver2:
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    environment:
      - DB_HOST=db2
      - DB_NAME=webserver2db
    networks:
      - webserver2-network
      - app-network

  webserver3:
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    environment:
      - DB_HOST=db3
      - DB_NAME=webserver3db
    networks:
      - webserver3-network
      - app-network

  reverse-proxy: 
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2
      - webserver3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  webserver1-network:
    driver: bridge
  webserver2-network:
    driver: bridge
  webserver3-network:
    driver: bridge