services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: michel
    networks:
      - app-network

  webserver1: 
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - app-network

  webserver2:
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - app-network

  webserver3:
    build: 
      context: ./web
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - app-network

  reverse-proxy: 
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - webserver1
      - webserver2
      - webserver3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge